name: Scan with local scanner

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

permissions:
  contents: read
  checks: write
  security-events: write # for github/codeql-action/upload-sarif


jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Contrast-Security-OSS/contrast-local-scan-action@v1.0.1
        with:
          apiUrl: ${{ secrets.CONTRAST__API__URL }}
          apiUserName: ${{ secrets.CONTRAST__API__USER_NAME }}
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          apiServiceKey: ${{ secrets.CONTRAST__API__SERVICE_KEY }}
          apiOrgId: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          severity: high
          checks: true
