name: Contrast Remote Scan

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

permissions:
  contents: read
  checks: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      # You may pin to the exact commit or the version.
      # uses: Contrast-Security-OSS/contrastscan-action@5b48a2c65f55b224e92e32e9cbc14b07a3d792ab
      - uses: Contrast-Security-OSS/contrastscan-action@v3.0.0
        with:
          # An agent API key provided by Contrast (required).
          apiKey: ${{ secrets.CONTRAST__API__API_KEY }}
          # User authorization credentials provided by Contrast (required).
          authHeader: 
          # The ID of your organization in Contrast (required).
          orgId: ${{ secrets.CONTRAST__API__ORGANIZATION_ID }}
          # The Artifact to Scan on the Contrast Platform.
          artifact: 
          # The name of the host. Includes the protocol section of the URL (https://). Defaults to https://ce.contrastsecurity.com. (optional)
          apiUrl: ${{ secrets.CONTRAST__API__URL }}
          # The name of the project you want to scan in Contrast.
          # projectName: 
          # The ID of your project in Contrast.
          # projectId: null
          # The language of your project.
          language: python
          # Set a specific time span (in seconds) before the function times out. The default timeout is 5 minutes if timeout is not set.
          # timeout: # optional, default is 300
          # Allows user to report vulnerabilities above a chosen severity level. Values for level are high, medium or low. (Note: Use this input in combination with the fail input, otherwise the action will exit)
          severity: MEDIUM
          # When set to true, fails the action if CVEs have been detected that match at least the severity option specified.
          fail: true
              
